import Head from 'next/head'
import {Menu} from 'components/Menu'
import {Sort} from "components/Sort"
import YoutubeContents from "components/Contents/Youtube/YoutubeContents"


export default function Home() {
  return (
    <>
      <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
        
      <Menu />
      <Sort />
      <YoutubeContents />
      
    </>
  );
}